FROM elasticsearch:latest

MAINTAINER Kunal Mangaraj <mangaraj.kunal@gmail.com>

EXPOSE 9200 9300

# docker build --no-cache -t elasticsearch .
# docker run -d -p 9200:9300 --name elasticsearch elasticsearch
